### ISSUE TITLE
Remotes option: overriden

### ISSUE THREAD

**Issue by stouf** [Wizcorp/component-proxy-install#2]
Let's say that I call the binary like this

``` bash
component-proxy-install -r https://mypersoremote.com -r https://oneotherpersoremote.com
```

This will actually fail in some situations. The reason of that is `Component` expects all the remotes to be listed in a coma-separated format (i.e `https://myremote1.com,https://myremote2.com`).
So, running the binary with at least one remote option (`-r`) will override the remotes defined internally by `component-proxy-install`, the local server being included. As a result, all the components expected to be retrieved via the local server will not because `component install` will _only_ use the last explicitly specified remote.

**Comment by bjornstar** [comment]
You can't specify the same command line argument twice in any program, but I understand what the actual problem is: if you use component-proxy-install, you cannot specify your own remotes.

**Comment by stouf** [comment]
Ah yeah, indeed, `commander` will not "stack" the several options (testing this with the `args` option was not a good choice... haha).
It could be worth to specify this in the README I think ? :)

**Comment by bjornstar** [comment]
You could fix it so that you can add more remotes.

**Comment by stouf** [comment]
Sure, that's actually the main reason of this issue, to keep a trace on it. For the moment, there is something else I need to finish as soon as possible, and I will go back to this quickly ;-)

**Comment by stouf** [comment]
See the Pull Request https://github.com/Wizcorp/component-proxy-install/pull/3
